import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from conjira_cli.setup_macos import (
    ensure_env_file,
    read_env_value,
    remove_env_value,
    resolve_keychain_target,
    resolve_default_paths,
    upsert_env_value,
)


class SetupMacOSTests(unittest.TestCase):
    def test_ensure_env_file_creates_non_secret_template(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            env_file = Path(tmp_dir) / "agent.env"

            ensure_env_file(env_file)

            text = env_file.read_text(encoding="utf-8")
            self.assertIn("Generated by conjira-setup-macos", text)
            self.assertIn("PATs are stored in macOS Keychain.", text)

    def test_upsert_env_value_updates_existing_key(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            env_file = Path(tmp_dir) / "agent.env"
            env_file.write_text("CONFLUENCE_BASE_URL=https://old.example.com\n", encoding="utf-8")

            upsert_env_value(env_file, "CONFLUENCE_BASE_URL", "https://new.example.com")

            self.assertEqual(
                env_file.read_text(encoding="utf-8"),
                "CONFLUENCE_BASE_URL=https://new.example.com\n",
            )

    def test_remove_env_value_drops_plain_pat_or_token_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            env_file = Path(tmp_dir) / "agent.env"
            env_file.write_text(
                "CONFLUENCE_PAT=/tmp/plain\n"
                "CONFLUENCE_PAT_FILE=/tmp/file.token\n"
                "CONFLUENCE_PAT_KEYCHAIN_SERVICE=conjira-cli\n",
                encoding="utf-8",
            )

            remove_env_value(env_file, "CONFLUENCE_PAT")
            remove_env_value(env_file, "CONFLUENCE_PAT_FILE")

            text = env_file.read_text(encoding="utf-8")
            self.assertNotIn("CONFLUENCE_PAT=", text)
            self.assertNotIn("CONFLUENCE_PAT_FILE=", text)
            self.assertIn("CONFLUENCE_PAT_KEYCHAIN_SERVICE=conjira-cli", text)

    def test_resolve_default_paths_prefers_explicit_env_file(self) -> None:
        env_file, staging_dir = resolve_default_paths("/tmp/demo/agent.env")

        self.assertEqual(env_file, Path("/tmp/demo/agent.env"))
        self.assertEqual(staging_dir, Path("/tmp/demo/exports"))

    def test_resolve_default_paths_uses_repo_root_from_env(self) -> None:
        with mock.patch.dict(os.environ, {"CONJIRA_SETUP_REPO_ROOT": "/tmp/conjira-repo"}, clear=False):
            env_file, staging_dir = resolve_default_paths(None)

        self.assertEqual(env_file, Path("/tmp/conjira-repo/local/agent.env"))
        self.assertEqual(staging_dir, Path("/tmp/conjira-repo/local/exports"))

    def test_resolve_default_paths_falls_back_to_cwd_local_dir(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            with mock.patch.dict(os.environ, {}, clear=True):
                with mock.patch("pathlib.Path.cwd", return_value=Path(tmp_dir)):
                    env_file, staging_dir = resolve_default_paths(None)

        self.assertEqual(env_file, Path(tmp_dir) / "local" / "agent.env")
        self.assertEqual(staging_dir, Path(tmp_dir) / "local" / "exports")

    def test_read_env_value_returns_existing_value(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            env_file = Path(tmp_dir) / "agent.env"
            env_file.write_text(
                "CONFLUENCE_PAT_KEYCHAIN_SERVICE=custom-service\n",
                encoding="utf-8",
            )

            value = read_env_value(env_file, "CONFLUENCE_PAT_KEYCHAIN_SERVICE")

        self.assertEqual(value, "custom-service")

    def test_resolve_keychain_target_uses_existing_env_values(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            env_file = Path(tmp_dir) / "agent.env"
            env_file.write_text(
                "CONFLUENCE_PAT_KEYCHAIN_SERVICE=custom-service\n"
                "CONFLUENCE_PAT_KEYCHAIN_ACCOUNT=custom-account\n",
                encoding="utf-8",
            )

            service, account = resolve_keychain_target(env_file, "CONFLUENCE", "confluence-prod")

        self.assertEqual(service, "custom-service")
        self.assertEqual(account, "custom-account")

    def test_resolve_keychain_target_falls_back_to_defaults(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            env_file = Path(tmp_dir) / "agent.env"

            service, account = resolve_keychain_target(env_file, "JIRA", "jira-prod")

        self.assertEqual(service, "conjira-cli")
        self.assertEqual(account, "jira-prod")
