from __future__ import annotations

import argparse
import getpass
import os
import subprocess
import sys
from pathlib import Path
from typing import Optional


HEADER = """\
conjira-cli macOS setup

This setup stores PATs in macOS Keychain and writes only non-secret settings
to your local env file.
"""


def ensure_env_file(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return
    path.write_text(
        "# Generated by conjira-setup-macos\n"
        "# This file should contain non-secret settings only.\n"
        "# PATs are stored in macOS Keychain.\n\n",
        encoding="utf-8",
    )


def upsert_env_value(path: Path, key: str, value: str) -> None:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        text = ""

    lines = text.splitlines()
    prefix = key + "="
    updated = False
    result = []
    for line in lines:
        if line.startswith(prefix):
            result.append(prefix + value)
            updated = True
        else:
            result.append(line)
    if not updated:
        result.append(prefix + value)

    path.write_text("\n".join(result).rstrip() + "\n", encoding="utf-8")


def remove_env_value(path: Path, key: str) -> None:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return

    prefix = key + "="
    lines = [line for line in text.splitlines() if not line.startswith(prefix)]
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def prompt_default(label: str, default: str) -> str:
    value = input(f"{label} [{default}]: ").strip()
    return value or default


def prompt_yes_no(label: str, default_yes: bool = True) -> bool:
    default = "y" if default_yes else "n"
    value = input(f"{label} (y/n) [{default}]: ").strip().lower()
    if not value:
        value = default
    return value in {"y", "yes"}


def prompt_optional(label: str) -> str:
    return input(f"{label}: ").strip()


def prompt_secret(label: str) -> str:
    return getpass.getpass(f"{label}: ").strip()


def read_env_value(path: Path, key: str) -> Optional[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None

    prefix = key + "="
    for line in text.splitlines():
        if line.startswith(prefix):
            value = line[len(prefix) :].strip()
            return value or None
    return None


def resolve_keychain_target(path: Path, prefix: str, default_account: str) -> tuple[str, str]:
    service = read_env_value(path, f"{prefix}_PAT_KEYCHAIN_SERVICE") or "conjira-cli"
    account = read_env_value(path, f"{prefix}_PAT_KEYCHAIN_ACCOUNT") or default_account
    return service, account


def prompt_required_secret(label: str) -> str:
    print(f"{label} input is hidden. Paste the token and press Enter.")
    return prompt_secret(label)


def keychain_store(service: str, account: str, secret: str) -> None:
    subprocess.run(
        [
            "security",
            "add-generic-password",
            "-U",
            "-s",
            service,
            "-a",
            account,
            "-w",
            secret,
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def run_auth_checks(env_file: Path, run_confluence: bool, run_jira: bool) -> None:
    base = [sys.executable, "-m", "conjira_cli", "--env-file", str(env_file)]
    if run_confluence:
        subprocess.run(base + ["auth-check"], check=True)
    if run_jira:
        subprocess.run(base + ["jira-auth-check"], check=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="conjira-setup-macos",
        description="Interactive macOS setup for conjira-cli",
    )
    parser.add_argument("--env-file")
    return parser


def resolve_default_paths(explicit_env_file: Optional[str]) -> tuple[Path, Path]:
    if explicit_env_file:
        env_file = Path(explicit_env_file).expanduser()
        return env_file, env_file.parent / "exports"

    repo_root = os.environ.get("CONJIRA_SETUP_REPO_ROOT")
    if repo_root:
        root = Path(repo_root).expanduser()
        return root / "local" / "agent.env", root / "local" / "exports"

    cwd_root = Path.cwd()
    return cwd_root / "local" / "agent.env", cwd_root / "local" / "exports"


def completion_hint(env_file: Path) -> str:
    default_env_file = Path.cwd() / "local" / "agent.env"
    if env_file == default_env_file:
        return (
            "Run conjira from this folder to auto-load ./local/agent.env.\n"
            "Try: conjira auth-check\n"
            "     conjira jira-auth-check"
        )
    return f"Try: conjira --env-file {env_file} auth-check"


def main(argv: Optional[list[str]] = None) -> int:
    if sys.platform != "darwin":
        print("This setup command currently supports macOS only.", file=sys.stderr)
        return 1

    parser = build_parser()
    args = parser.parse_args(argv)

    env_file, staging_dir = resolve_default_paths(args.env_file)

    ensure_env_file(env_file)
    staging_dir.mkdir(parents=True, exist_ok=True)

    print()
    print(HEADER)
    print(f"Target env file: {env_file}")
    print()

    configure_confluence = prompt_yes_no("Configure Confluence?", True)
    configure_jira = prompt_yes_no("Configure Jira?", True)
    configured_any = False

    if configure_confluence:
        configured_any = True
        base_url = prompt_default("Confluence base URL", "https://confluence.example.com")
        service, account = resolve_keychain_target(env_file, "CONFLUENCE", "confluence-prod")
        print(f"Confluence Keychain target: service={service}, account={account}")
        pat = prompt_required_secret("Enter Confluence PAT")
        if not pat:
            print("Confluence PAT is required when Confluence setup is enabled.", file=sys.stderr)
            return 1

        keychain_store(service, account, pat)
        remove_env_value(env_file, "CONFLUENCE_PAT")
        remove_env_value(env_file, "CONFLUENCE_PAT_FILE")
        upsert_env_value(env_file, "CONFLUENCE_BASE_URL", base_url)
        upsert_env_value(env_file, "CONFLUENCE_PAT_KEYCHAIN_SERVICE", service)
        upsert_env_value(env_file, "CONFLUENCE_PAT_KEYCHAIN_ACCOUNT", account)
        upsert_env_value(env_file, "CONFLUENCE_EXPORT_STAGING_DIR", str(staging_dir))

        text = env_file.read_text(encoding="utf-8")
        if "CONFLUENCE_EXPORT_DEFAULT_DIR=" not in text:
            export_dir = prompt_optional(
                "Optional Confluence export default directory (leave blank to skip)"
            )
            if export_dir:
                upsert_env_value(env_file, "CONFLUENCE_EXPORT_DEFAULT_DIR", export_dir)

    if configure_jira:
        configured_any = True
        base_url = prompt_default("Jira base URL", "https://jira.example.com")
        service, account = resolve_keychain_target(env_file, "JIRA", "jira-prod")
        print(f"Jira Keychain target: service={service}, account={account}")
        pat = prompt_required_secret("Enter Jira PAT")
        if not pat:
            print("Jira PAT is required when Jira setup is enabled.", file=sys.stderr)
            return 1

        keychain_store(service, account, pat)
        remove_env_value(env_file, "JIRA_PAT")
        remove_env_value(env_file, "JIRA_PAT_FILE")
        upsert_env_value(env_file, "JIRA_BASE_URL", base_url)
        upsert_env_value(env_file, "JIRA_PAT_KEYCHAIN_SERVICE", service)
        upsert_env_value(env_file, "JIRA_PAT_KEYCHAIN_ACCOUNT", account)

    if not configured_any:
        print("Nothing selected. No changes were made.")
        return 0

    print()
    print(f"Saved non-secret settings to: {env_file}")
    print("PATs were stored in macOS Keychain.")
    print()

    if prompt_yes_no("Run auth checks now?", True):
        run_auth_checks(env_file, configure_confluence, configure_jira)

    print()
    print("Setup complete.")
    print(completion_hint(env_file))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
